const { Workout } = require("../models");

const workoutData = [
  {
    name: "swimming",
    filename: "swimmers-gd79b7b5ac_1920.jpg",
    description: "Works out your chest, arms, legs, glutes and core. Consistent swimming on your back will help these muscle groups grow stronger.",
    difficulty_level: "moderate",
    equipment: "pool",
    reps: "10",
    username: "Aliya_jay",
    activity_id: 1,
    user_id: 1,
  },
  {
    name: "Jump Rope",
    filename: "swimmers-gd79b7b5ac_1920.jpg",
    description: "test",
    difficulty_level: "moderate",
    equipment: "rope",
    reps: "10",
    username: "Aliya_jay",
    activity_id: 1,
    user_id: 1,
  },
  {
    name: "Push-Up",
    filename: "swimmers-gd79b7b5ac_1920.jpg",
    description: "test",
    difficulty_level: "intense",
    equipment: "a moderate-heavy weight",
    reps: "30 to 60 secs",
    username: "Aliya_jay",
    activity_id: 2,
    user_id: 1,
  },
  {
    name: "Deadlift",
    filename: "swimmers-gd79b7b5ac_1920.jpg",
    description: "test",
    difficulty_level: "intense",
    equipment: "a moderate-heavy weight",
    reps: "30 to 60 secs",
    username: "Aliya_jay",
    activity_id: 2,
    user_id: 1,
  },
  {
    name: "Pop Squat",
    filename: "swimmers-gd79b7b5ac_1920.jpg",
    description: "test",
    difficulty_level: "intense",
    equipment: "rope",
    reps: "10",
    username: "Aliya_jay",
    activity_id: 2,
    user_id: 1,
  },
  {
    name: "Split Squat Jump",
    filename: "swimmers-gd79b7b5ac_1920.jpg",
    description: "test",
    difficulty_level: "intense",
    equipment: "rope",
    reps: "10",
    username: "Aliya_jay",
    activity_id: 4,
    user_id: 1,
  },

  {
    name: "Vinyasa yoga",
    filename: "swimmers-gd79b7b5ac_1920.jpg",
    description: "test",
    difficulty_level: "easy",
    equipment: "mat",
    reps: "10",
    username: "Aliya_jay",
    activity_id: 3,
    user_id: 1,
  },
  {
    name: "Kundalini yoga",
    filename: "swimmers-gd79b7b5ac_1920.jpg",
    description: "A kundalini class will really work your core and breath with fast-moving, invigorating postures and breath exercises.",
    difficulty_level: "Intense",
    equipment: "mat",
    reps: "10",
    username: "Aliya_jay",
    activity_id: 3,
    user_id: 1,
  },
];

const seedWorkout = () => Workout.bulkCreate(workoutData);

module.exports = seedWorkout;
